# Form implementation generated from reading ui file 'sofistik.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.db_name = QtWidgets.QLabel(self.centralwidget)
        self.db_name.setGeometry(QtCore.QRect(20, 10, 111, 51))
        self.db_name.setText("")
        self.db_name.setWordWrap(True)
        self.db_name.setObjectName("db_name")
        self.OKButton = QtWidgets.QPushButton(self.centralwidget)
        self.OKButton.setGeometry(QtCore.QRect(640, 20, 141, 61))
        self.OKButton.setStyleSheet("background-color: rgb(89, 255, 0);")
        self.OKButton.setObjectName("OKButton")
        self.plate_picture = QtWidgets.QLabel(self.centralwidget)
        self.plate_picture.setGeometry(QtCore.QRect(0, 130, 911, 441))
        self.plate_picture.setText("")
        self.plate_picture.setPixmap(QtGui.QPixmap("../sofistik/result/test_image_from_python.bmp"))
        self.plate_picture.setScaledContents(True)
        self.plate_picture.setObjectName("plate_picture")
        self.plate_group = QtWidgets.QLabel(self.centralwidget)
        self.plate_group.setGeometry(QtCore.QRect(120, 10, 71, 20))
        self.plate_group.setText("")
        self.plate_group.setObjectName("plate_group")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 916, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_database = QtGui.QAction(MainWindow)
        self.actionOpen_database.setObjectName("actionOpen_database")
        self.actionabout = QtGui.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionexit = QtGui.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menuFile.addAction(self.actionOpen_database)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionexit)
        self.menuhelp.addAction(self.actionabout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OKButton.setText(_translate("MainWindow", "OK"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))
        self.actionOpen_database.setText(_translate("MainWindow", "Open database..."))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionexit.setText(_translate("MainWindow", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
