# Form implementation generated from reading ui file 'sofistik.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Ask_plate(object):
    def setupUi(self, Ask_plate):
        Ask_plate.setObjectName("Ask_plate")
        Ask_plate.setEnabled(True)
        Ask_plate.resize(169, 94)
        self.plate_number_lable_text = QtWidgets.QLabel(Ask_plate)
        self.plate_number_lable_text.setGeometry(QtCore.QRect(10, 10, 161, 20))
        self.plate_number_lable_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.plate_number_lable_text.setObjectName("plate_number_lable_text")
        self.plate_number = QtWidgets.QSpinBox(Ask_plate)
        self.plate_number.setGeometry(QtCore.QRect(20, 40, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.plate_number.setFont(font)
        self.plate_number.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.plate_number.setObjectName("plate_number")
        self.select_plate_OK = QtWidgets.QPushButton(Ask_plate)
        self.select_plate_OK.setGeometry(QtCore.QRect(90, 30, 71, 51))
        self.select_plate_OK.setStyleSheet("background-color: rgb(89, 255, 0);")
        self.select_plate_OK.setObjectName("select_plate_OK")
        self.select_plate_OK_pressed = QtGui.QAction(Ask_plate)
        self.select_plate_OK_pressed.setObjectName("select_plate_OK_pressed")

        self.retranslateUi(Ask_plate)
        QtCore.QMetaObject.connectSlotsByName(Ask_plate)

    def retranslateUi(self, Ask_plate):
        _translate = QtCore.QCoreApplication.translate
        Ask_plate.setWindowTitle(_translate("Ask_plate", "Dialog"))
        self.plate_number_lable_text.setText(_translate("Ask_plate", "Введите номер пластины"))
        self.select_plate_OK.setText(_translate("Ask_plate", "OK"))
        self.select_plate_OK_pressed.setText(_translate("Ask_plate", "plate_selected"))
        self.select_plate_OK_pressed.setToolTip(_translate("Ask_plate", "<html><head/><body><p>Select plate and press OK</p></body></html>"))
        self.select_plate_OK_pressed.setShortcut(_translate("Ask_plate", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ask_plate = QtWidgets.QDialog()
    ui = Ui_Ask_plate()
    ui.setupUi(Ask_plate)
    Ask_plate.show()
    sys.exit(app.exec())
