"""create_quads_table

Revision ID: 390181a3e0f0
Revises: 
Create Date: 2021-11-05 16:04:49.228008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390181a3e0f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quad_number', sa.Integer(), nullable=False),
    sa.Column('node_0', sa.String(length=255), nullable=False),
    sa.Column('node_1', sa.String(length=255), nullable=False),
    sa.Column('node_2', sa.String(length=255), nullable=False),
    sa.Column('node_3', sa.String(length=255), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('bending_moment_mxx', sa.Integer(), nullable=False),
    sa.Column('bending_moment_myy', sa.Integer(), nullable=False),
    sa.Column('bending_moment_mxy', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quad_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quads')
    # ### end Alembic commands ###
