from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog, QMainWindow

from sofistik.sofistik_discover import Sofistik


class MainWindowUI:
    """ Main window from PyQt6 \n
    label: db_name \n
    button: OKButton \n
    picture: plate_picture \n
    label: plate_group \n
    action: actionOpen_database \n
    action: actionexit \n
    action: actionabout \n
    """

    def base_setup_ui(self, main_window: QMainWindow) -> None:
        main_window.setObjectName("main_window")
        main_window.resize(1162, 773)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.head_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.head_label.sizePolicy().hasHeightForWidth())
        self.head_label.setSizePolicy(sizePolicy)
        self.head_label.setObjectName("head_label")
        self.horizontalLayout_3.addWidget(self.head_label)
        self.db_name = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_name.sizePolicy().hasHeightForWidth())
        self.db_name.setSizePolicy(sizePolicy)
        self.db_name.setObjectName("db_name")
        self.horizontalLayout_3.addWidget(self.db_name)
        self.plate_group = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plate_group.sizePolicy().hasHeightForWidth())
        self.plate_group.setSizePolicy(sizePolicy)
        self.plate_group.setObjectName("plate_group")
        self.horizontalLayout_3.addWidget(self.plate_group)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 2, 3)
        self.vertical_line = QtWidgets.QFrame(self.centralwidget)
        self.vertical_line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.vertical_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.vertical_line.setObjectName("vertical_line")
        self.gridLayout_3.addWidget(self.vertical_line, 1, 1, 2, 2)
        self.get_info_area = QtWidgets.QScrollArea(self.centralwidget)
        self.get_info_area.setMinimumSize(QtCore.QSize(373, 0))
        self.get_info_area.setWidgetResizable(True)
        self.get_info_area.setObjectName("get_info_area")
        self.get_info_widget = QtWidgets.QWidget()
        self.get_info_widget.setGeometry(QtCore.QRect(0, 0, 564, 654))
        self.get_info_widget.setObjectName("get_info_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.get_info_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.external_forces_label = QtWidgets.QLabel(self.get_info_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.external_forces_label.setFont(font)
        self.external_forces_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.external_forces_label.setObjectName("external_forces_label")
        self.verticalLayout.addWidget(self.external_forces_label)
        self.get_info_horizontal_layout_1 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_1.setObjectName("get_info_horizontal_layout_1")
        self.label_text_1_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_1_1.sizePolicy().hasHeightForWidth())
        self.label_text_1_1.setSizePolicy(sizePolicy)
        self.label_text_1_1.setObjectName("label_text_1_1")
        self.get_info_horizontal_layout_1.addWidget(self.label_text_1_1)
        self.label_text_1_2 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_1_2.sizePolicy().hasHeightForWidth())
        self.label_text_1_2.setSizePolicy(sizePolicy)
        self.label_text_1_2.setObjectName("label_text_1_2")
        self.get_info_horizontal_layout_1.addWidget(self.label_text_1_2)
        self.lineEdit_1_1 = QtWidgets.QLineEdit(self.get_info_widget)
        self.lineEdit_1_1.setObjectName("lineEdit_1_1")
        self.get_info_horizontal_layout_1.addWidget(self.lineEdit_1_1)
        self.label_text_1_3 = QtWidgets.QLabel(self.get_info_widget)
        self.label_text_1_3.setObjectName("label_text_1_3")
        self.get_info_horizontal_layout_1.addWidget(self.label_text_1_3)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_1)
        self.get_info_horizontal_layout_2 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_2.setObjectName("get_info_horizontal_layout_2")
        self.label_text_2_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_2_1.sizePolicy().hasHeightForWidth())
        self.label_text_2_1.setSizePolicy(sizePolicy)
        self.label_text_2_1.setObjectName("label_text_2_1")
        self.get_info_horizontal_layout_2.addWidget(self.label_text_2_1)
        self.label_text_2_2 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_2_2.sizePolicy().hasHeightForWidth())
        self.label_text_2_2.setSizePolicy(sizePolicy)
        self.label_text_2_2.setObjectName("label_text_2_2")
        self.get_info_horizontal_layout_2.addWidget(self.label_text_2_2)
        self.lineEdit_2_1 = QtWidgets.QLineEdit(self.get_info_widget)
        self.lineEdit_2_1.setObjectName("lineEdit_2_1")
        self.get_info_horizontal_layout_2.addWidget(self.lineEdit_2_1)
        self.label_text_2_3 = QtWidgets.QLabel(self.get_info_widget)
        self.label_text_2_3.setObjectName("label_text_2_3")
        self.get_info_horizontal_layout_2.addWidget(self.label_text_2_3)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_2)
        self.get_info_horizontal_layout_3 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_3.setObjectName("get_info_horizontal_layout_3")
        self.label_text_3_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_3_1.sizePolicy().hasHeightForWidth())
        self.label_text_3_1.setSizePolicy(sizePolicy)
        self.label_text_3_1.setObjectName("label_text_3_1")
        self.get_info_horizontal_layout_3.addWidget(self.label_text_3_1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.get_info_widget)
        self.checkBox_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.checkBox_3.setText("    ")
        self.checkBox_3.setObjectName("checkBox_3")
        self.get_info_horizontal_layout_3.addWidget(self.checkBox_3)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_3)
        self.get_info_horizontal_layout_4 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_4.setObjectName("get_info_horizontal_layout_4")
        self.label_text_4_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_4_1.sizePolicy().hasHeightForWidth())
        self.label_text_4_1.setSizePolicy(sizePolicy)
        self.label_text_4_1.setObjectName("label_text_4_1")
        self.get_info_horizontal_layout_4.addWidget(self.label_text_4_1)
        self.label_text_4_2 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_4_2.sizePolicy().hasHeightForWidth())
        self.label_text_4_2.setSizePolicy(sizePolicy)
        self.label_text_4_2.setObjectName("label_text_4_2")
        self.get_info_horizontal_layout_4.addWidget(self.label_text_4_2)
        self.line_edit_4_1 = QtWidgets.QLineEdit(self.get_info_widget)
        self.line_edit_4_1.setEnabled(False)
        self.line_edit_4_1.setObjectName("line_edit_4_1")
        self.get_info_horizontal_layout_4.addWidget(self.line_edit_4_1)
        self.label_text_4_3 = QtWidgets.QLabel(self.get_info_widget)
        self.label_text_4_3.setObjectName("label_text_4_3")
        self.get_info_horizontal_layout_4.addWidget(self.label_text_4_3)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_4)
        self.get_info_horizontal_layout_5 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_5.setObjectName("get_info_horizontal_layout_5")
        self.label_text_5_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_5_1.sizePolicy().hasHeightForWidth())
        self.label_text_5_1.setSizePolicy(sizePolicy)
        self.label_text_5_1.setObjectName("label_text_5_1")
        self.get_info_horizontal_layout_5.addWidget(self.label_text_5_1)
        self.label_text_5_2 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_5_2.sizePolicy().hasHeightForWidth())
        self.label_text_5_2.setSizePolicy(sizePolicy)
        self.label_text_5_2.setObjectName("label_text_5_2")
        self.get_info_horizontal_layout_5.addWidget(self.label_text_5_2)
        self.line_edit_5_1 = QtWidgets.QLineEdit(self.get_info_widget)
        self.line_edit_5_1.setEnabled(False)
        self.line_edit_5_1.setObjectName("line_edit_5_1")
        self.get_info_horizontal_layout_5.addWidget(self.line_edit_5_1)
        self.label_text_5_3 = QtWidgets.QLabel(self.get_info_widget)
        self.label_text_5_3.setObjectName("label_text_5_3")
        self.get_info_horizontal_layout_5.addWidget(self.label_text_5_3)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_5)
        self.geo_label = QtWidgets.QLabel(self.get_info_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.geo_label.setFont(font)
        self.geo_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.geo_label.setObjectName("geo_label")
        self.verticalLayout.addWidget(self.geo_label)
        self.get_info_horizontal_layout_6 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_6.setObjectName("get_info_horizontal_layout_6")
        self.label_text_6_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_6_1.sizePolicy().hasHeightForWidth())
        self.label_text_6_1.setSizePolicy(sizePolicy)
        self.label_text_6_1.setObjectName("label_text_6_1")
        self.get_info_horizontal_layout_6.addWidget(self.label_text_6_1)
        self.label_text_6_2 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_6_2.sizePolicy().hasHeightForWidth())
        self.label_text_6_2.setSizePolicy(sizePolicy)
        self.label_text_6_2.setObjectName("label_text_6_2")
        self.get_info_horizontal_layout_6.addWidget(self.label_text_6_2)
        self.line_edit_6_1 = QtWidgets.QLineEdit(self.get_info_widget)
        self.line_edit_6_1.setObjectName("line_edit_6_1")
        self.get_info_horizontal_layout_6.addWidget(self.line_edit_6_1)
        self.label_text_6_3 = QtWidgets.QLabel(self.get_info_widget)
        self.label_text_6_3.setObjectName("label_text_6_3")
        self.get_info_horizontal_layout_6.addWidget(self.label_text_6_3)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_6)
        self.get_info_horizontal_layout_7 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_7.setObjectName("get_info_horizontal_layout_7")
        self.label_text_7_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_7_1.sizePolicy().hasHeightForWidth())
        self.label_text_7_1.setSizePolicy(sizePolicy)
        self.label_text_7_1.setObjectName("label_text_7_1")
        self.get_info_horizontal_layout_7.addWidget(self.label_text_7_1)
        self.label_text_7_2 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_7_2.sizePolicy().hasHeightForWidth())
        self.label_text_7_2.setSizePolicy(sizePolicy)
        self.label_text_7_2.setObjectName("label_text_7_2")
        self.get_info_horizontal_layout_7.addWidget(self.label_text_7_2)
        self.line_edit_7_1 = QtWidgets.QLineEdit(self.get_info_widget)
        self.line_edit_7_1.setObjectName("line_edit_7_1")
        self.get_info_horizontal_layout_7.addWidget(self.line_edit_7_1)
        self.label_text_7_3 = QtWidgets.QLabel(self.get_info_widget)
        self.label_text_7_3.setObjectName("label_text_7_3")
        self.get_info_horizontal_layout_7.addWidget(self.label_text_7_3)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_7)
        self.get_info_horizontal_layout_8 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_8.setObjectName("get_info_horizontal_layout_8")
        self.label_text_8_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_8_1.sizePolicy().hasHeightForWidth())
        self.label_text_8_1.setSizePolicy(sizePolicy)
        self.label_text_8_1.setObjectName("label_text_8_1")
        self.get_info_horizontal_layout_8.addWidget(self.label_text_8_1)
        self.label_text_8_2 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_8_2.sizePolicy().hasHeightForWidth())
        self.label_text_8_2.setSizePolicy(sizePolicy)
        self.label_text_8_2.setObjectName("label_text_8_2")
        self.get_info_horizontal_layout_8.addWidget(self.label_text_8_2)
        self.line_edit_8_1 = QtWidgets.QLineEdit(self.get_info_widget)
        self.line_edit_8_1.setObjectName("line_edit_8_1")
        self.get_info_horizontal_layout_8.addWidget(self.line_edit_8_1)
        self.label_text_8_3 = QtWidgets.QLabel(self.get_info_widget)
        self.label_text_8_3.setObjectName("label_text_8_3")
        self.get_info_horizontal_layout_8.addWidget(self.label_text_8_3)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_8)
        self.get_info_horizontal_layout_9 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_9.setObjectName("get_info_horizontal_layout_9")
        self.label_text_9_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_9_1.sizePolicy().hasHeightForWidth())
        self.label_text_9_1.setSizePolicy(sizePolicy)
        self.label_text_9_1.setObjectName("label_text_9_1")
        self.get_info_horizontal_layout_9.addWidget(self.label_text_9_1)
        self.label_text_9_2 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_9_2.sizePolicy().hasHeightForWidth())
        self.label_text_9_2.setSizePolicy(sizePolicy)
        self.label_text_9_2.setObjectName("label_text_9_2")
        self.get_info_horizontal_layout_9.addWidget(self.label_text_9_2)
        self.line_edit_9_1 = QtWidgets.QLineEdit(self.get_info_widget)
        self.line_edit_9_1.setObjectName("line_edit_9_1")
        self.get_info_horizontal_layout_9.addWidget(self.line_edit_9_1)
        self.label_text_9_3 = QtWidgets.QLabel(self.get_info_widget)
        self.label_text_9_3.setObjectName("label_text_9_3")
        self.get_info_horizontal_layout_9.addWidget(self.label_text_9_3)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_9)
        self.get_info_horizontal_layout_10 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_10.setObjectName("get_info_horizontal_layout_10")
        self.label_text_10_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_10_1.sizePolicy().hasHeightForWidth())
        self.label_text_10_1.setSizePolicy(sizePolicy)
        self.label_text_10_1.setObjectName("label_text_10_1")
        self.get_info_horizontal_layout_10.addWidget(self.label_text_10_1)
        self.label_text_10_2 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_10_2.sizePolicy().hasHeightForWidth())
        self.label_text_10_2.setSizePolicy(sizePolicy)
        self.label_text_10_2.setObjectName("label_text_10_2")
        self.get_info_horizontal_layout_10.addWidget(self.label_text_10_2)
        self.line_edit_10_1 = QtWidgets.QLineEdit(self.get_info_widget)
        self.line_edit_10_1.setObjectName("line_edit_10_1")
        self.get_info_horizontal_layout_10.addWidget(self.line_edit_10_1)
        self.label_text_10_3 = QtWidgets.QLabel(self.get_info_widget)
        self.label_text_10_3.setObjectName("label_text_10_3")
        self.get_info_horizontal_layout_10.addWidget(self.label_text_10_3)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_10)
        self.get_info_horizontal_layout_11 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_11.setObjectName("get_info_horizontal_layout_11")
        self.label_text_11_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_11_1.sizePolicy().hasHeightForWidth())
        self.label_text_11_1.setSizePolicy(sizePolicy)
        self.label_text_11_1.setObjectName("label_text_11_1")
        self.get_info_horizontal_layout_11.addWidget(self.label_text_11_1)
        self.label_text_11_2 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_11_2.sizePolicy().hasHeightForWidth())
        self.label_text_11_2.setSizePolicy(sizePolicy)
        self.label_text_11_2.setObjectName("label_text_11_2")
        self.get_info_horizontal_layout_11.addWidget(self.label_text_11_2)
        self.line_edit_11_1 = QtWidgets.QLineEdit(self.get_info_widget)
        self.line_edit_11_1.setObjectName("line_edit_11_1")
        self.get_info_horizontal_layout_11.addWidget(self.line_edit_11_1)
        self.label_text_11_3 = QtWidgets.QLabel(self.get_info_widget)
        self.label_text_11_3.setObjectName("label_text_11_3")
        self.get_info_horizontal_layout_11.addWidget(self.label_text_11_3)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_11)
        self.get_info_horizontal_layout_12 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_12.setObjectName("get_info_horizontal_layout_12")
        self.label_text_12_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_12_1.sizePolicy().hasHeightForWidth())
        self.label_text_12_1.setSizePolicy(sizePolicy)
        self.label_text_12_1.setObjectName("label_text_12_1")
        self.get_info_horizontal_layout_12.addWidget(self.label_text_12_1)
        self.label_text_12_2 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_12_2.sizePolicy().hasHeightForWidth())
        self.label_text_12_2.setSizePolicy(sizePolicy)
        self.label_text_12_2.setObjectName("label_text_12_2")
        self.get_info_horizontal_layout_12.addWidget(self.label_text_12_2)
        self.line_edit_12_1 = QtWidgets.QLineEdit(self.get_info_widget)
        self.line_edit_12_1.setObjectName("line_edit_12_1")
        self.get_info_horizontal_layout_12.addWidget(self.line_edit_12_1)
        self.label_text_12_3 = QtWidgets.QLabel(self.get_info_widget)
        self.label_text_12_3.setObjectName("label_text_12_3")
        self.get_info_horizontal_layout_12.addWidget(self.label_text_12_3)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_12)
        self.beton_options_label = QtWidgets.QLabel(self.get_info_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.beton_options_label.setFont(font)
        self.beton_options_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.beton_options_label.setObjectName("beton_options_label")
        self.verticalLayout.addWidget(self.beton_options_label)
        self.get_info_horizontal_layout_13 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_13.setObjectName("get_info_horizontal_layout_13")
        self.label_text_13_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_13_1.sizePolicy().hasHeightForWidth())
        self.label_text_13_1.setSizePolicy(sizePolicy)
        self.label_text_13_1.setObjectName("label_text_13_1")
        self.get_info_horizontal_layout_13.addWidget(self.label_text_13_1)
        self.comboBox_13 = QtWidgets.QComboBox(self.get_info_widget)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.get_info_horizontal_layout_13.addWidget(self.comboBox_13)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_13)
        self.get_info_horizontal_layout_14 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_14.setObjectName("get_info_horizontal_layout_14")
        self.label_text_14_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_14_1.sizePolicy().hasHeightForWidth())
        self.label_text_14_1.setSizePolicy(sizePolicy)
        self.label_text_14_1.setObjectName("label_text_14_1")
        self.get_info_horizontal_layout_14.addWidget(self.label_text_14_1)
        self.comboBox_14 = QtWidgets.QComboBox(self.get_info_widget)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.get_info_horizontal_layout_14.addWidget(self.comboBox_14)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_14)
        self.restrictions_label = QtWidgets.QLabel(self.get_info_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.restrictions_label.setFont(font)
        self.restrictions_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.restrictions_label.setObjectName("restrictions_label")
        self.verticalLayout.addWidget(self.restrictions_label)
        self.get_info_horizontal_layout_15 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_15.setObjectName("get_info_horizontal_layout_15")
        self.label_text_15_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_15_1.sizePolicy().hasHeightForWidth())
        self.label_text_15_1.setSizePolicy(sizePolicy)
        self.label_text_15_1.setObjectName("label_text_15_1")
        self.get_info_horizontal_layout_15.addWidget(self.label_text_15_1)
        self.label_text_15_2 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_15_2.sizePolicy().hasHeightForWidth())
        self.label_text_15_2.setSizePolicy(sizePolicy)
        self.label_text_15_2.setObjectName("label_text_15_2")
        self.get_info_horizontal_layout_15.addWidget(self.label_text_15_2)
        self.line_edit_15_1 = QtWidgets.QLineEdit(self.get_info_widget)
        self.line_edit_15_1.setObjectName("line_edit_15_1")
        self.get_info_horizontal_layout_15.addWidget(self.line_edit_15_1)
        self.label_text_15_3 = QtWidgets.QLabel(self.get_info_widget)
        self.label_text_15_3.setObjectName("label_text_15_3")
        self.get_info_horizontal_layout_15.addWidget(self.label_text_15_3)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_15)
        self.get_info_horizontal_layout_16 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_16.setObjectName("get_info_horizontal_layout_16")
        self.label_text_16_1 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_16_1.sizePolicy().hasHeightForWidth())
        self.label_text_16_1.setSizePolicy(sizePolicy)
        self.label_text_16_1.setObjectName("label_text_16_1")
        self.get_info_horizontal_layout_16.addWidget(self.label_text_16_1)
        self.label_text_16_2 = QtWidgets.QLabel(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_16_2.sizePolicy().hasHeightForWidth())
        self.label_text_16_2.setSizePolicy(sizePolicy)
        self.label_text_16_2.setObjectName("label_text_16_2")
        self.get_info_horizontal_layout_16.addWidget(self.label_text_16_2)
        self.line_edit_16 = QtWidgets.QLineEdit(self.get_info_widget)
        self.line_edit_16.setObjectName("line_edit_16")
        self.get_info_horizontal_layout_16.addWidget(self.line_edit_16)
        self.label_text_16_3 = QtWidgets.QLabel(self.get_info_widget)
        self.label_text_16_3.setObjectName("label_text_16_3")
        self.get_info_horizontal_layout_16.addWidget(self.label_text_16_3)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_16)
        self.get_info_horizontal_layout_17 = QtWidgets.QHBoxLayout()
        self.get_info_horizontal_layout_17.setObjectName("get_info_horizontal_layout_17")
        self.calculate_button = QtWidgets.QPushButton(self.get_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculate_button.sizePolicy().hasHeightForWidth())
        self.calculate_button.setSizePolicy(sizePolicy)
        self.calculate_button.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.calculate_button.setObjectName("calculate_button")
        self.get_info_horizontal_layout_17.addWidget(self.calculate_button)
        self.in_another_window_show = QtWidgets.QCheckBox(self.get_info_widget)
        self.in_another_window_show.setObjectName("in_another_window_show")
        self.get_info_horizontal_layout_17.addWidget(self.in_another_window_show)
        self.verticalLayout.addLayout(self.get_info_horizontal_layout_17)
        self.get_info_area.setWidget(self.get_info_widget)
        self.gridLayout_3.addWidget(self.get_info_area, 2, 0, 1, 1)
        self.total_pictures_widget = QtWidgets.QVBoxLayout()
        self.total_pictures_widget.setObjectName("total_pictures_widget")
        self.picture_preview = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.picture_preview.sizePolicy().hasHeightForWidth())
        self.picture_preview.setSizePolicy(sizePolicy)
        self.picture_preview.setMinimumSize(QtCore.QSize(421, 200))
        self.picture_preview.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.picture_preview.setBaseSize(QtCore.QSize(579, 300))
        self.picture_preview.setObjectName("picture_preview")
        self.picture_preview_widget = QtWidgets.QWidget(self.picture_preview)
        self.picture_preview_widget.setGeometry(QtCore.QRect(0, -10, 421, 211))
        self.picture_preview_widget.setMinimumSize(QtCore.QSize(421, 211))
        self.picture_preview_widget.setObjectName("picture_preview_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.picture_preview_widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pic_preview_label = QtWidgets.QLabel(self.picture_preview_widget)
        self.pic_preview_label.setText("")
        self.pic_preview_label.setPixmap(
            QtGui.QPixmap("../../../.designer/sofistik/result/test_image_from_python.bmp"))
        self.pic_preview_label.setScaledContents(True)
        self.pic_preview_label.setObjectName("pic_preview_label")
        self.gridLayout_4.addWidget(self.pic_preview_label, 0, 0, 1, 1)
        self.total_pictures_widget.addWidget(self.picture_preview)
        self.picture_horizontal_line = QtWidgets.QFrame(self.centralwidget)
        self.picture_horizontal_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.picture_horizontal_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.picture_horizontal_line.setObjectName("picture_horizontal_line")
        self.total_pictures_widget.addWidget(self.picture_horizontal_line)
        self.large_picture = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.large_picture.sizePolicy().hasHeightForWidth())
        self.large_picture.setSizePolicy(sizePolicy)
        self.large_picture.setObjectName("large_picture")
        self.gridLayout = QtWidgets.QGridLayout(self.large_picture)
        self.gridLayout.setObjectName("gridLayout")
        self.large_picture_scroll_area = QtWidgets.QScrollArea(self.large_picture)
        self.large_picture_scroll_area.setWidgetResizable(True)
        self.large_picture_scroll_area.setObjectName("large_picture_scroll_area")
        self.large_picture_scroll_area_widget = QtWidgets.QWidget()
        self.large_picture_scroll_area_widget.setGeometry(QtCore.QRect(0, 0, 544, 419))
        self.large_picture_scroll_area_widget.setObjectName("large_picture_scroll_area_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.large_picture_scroll_area_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.large_picture_label = QtWidgets.QLabel(self.large_picture_scroll_area_widget)
        self.large_picture_label.setText("")
        self.large_picture_label.setPixmap(
            QtGui.QPixmap("../../../.designer/sofistik/result/test_image_from_python.bmp"))
        self.large_picture_label.setScaledContents(True)
        self.large_picture_label.setObjectName("large_picture_label")
        self.gridLayout_2.addWidget(self.large_picture_label, 0, 0, 1, 1)
        self.large_picture_scroll_area.setWidget(self.large_picture_scroll_area_widget)
        self.gridLayout.addWidget(self.large_picture_scroll_area, 0, 0, 1, 1)
        self.total_pictures_widget.addWidget(self.large_picture)
        self.gridLayout_3.addLayout(self.total_pictures_widget, 2, 2, 1, 1)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1162, 22))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.info_menu = QtWidgets.QMenu(self.menubar)
        self.info_menu.setObjectName("info_menu")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.choose_db_menu = QtGui.QAction(main_window)
        self.choose_db_menu.setObjectName("choose_db_menu")
        self.exit_menu = QtGui.QAction(main_window)
        self.exit_menu.setObjectName("exit_menu")
        self.about_menu = QtGui.QAction(main_window)
        self.about_menu.setObjectName("about_menu")
        self.file_menu.addAction(self.choose_db_menu)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.exit_menu)
        self.info_menu.addAction(self.about_menu)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.info_menu.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Проверка на образование трещин и ширины их раскрытия"))
        self.head_label.setText(_translate("main_window", "Методика расчета принята согласно СП 63.13330.2012.\n"
                                                         "Рассматриваются трещины нормальные к продольной оси элемента.\n"
                                                         "Элемент изгибаемый. Сечение прямоугольное."))
        self.db_name.setText(_translate("main_window", "TextLabel"))
        self.plate_group.setText(_translate("main_window", "TextLabel"))
        self.external_forces_label.setText(_translate("main_window", "Внешние усилия"))
        self.label_text_1_1.setText(_translate("main_window", "Момент от полной нагрузки:            "))
        self.label_text_1_2.setText(_translate("main_window", "M"))
        self.lineEdit_1_1.setText(_translate("main_window", "277000"))
        self.label_text_1_3.setText(_translate("main_window", "кг·см (1 тс·м = 10^5 кг·см"))
        self.label_text_2_1.setText(_translate("main_window", "Момент от постоянной и длительной нагрузки:"))
        self.label_text_2_2.setText(_translate("main_window", "M1"))
        self.lineEdit_2_1.setText(_translate("main_window", "2500000"))
        self.label_text_2_3.setText(_translate("main_window", "кг·см"))
        self.label_text_3_1.setText(_translate("main_window", "Учесть продольную силу:"))
        self.label_text_4_1.setText(_translate("main_window", "Продольная сила от полной нагрузки: \n"
                                                             " ((сжатие: \"+\"; растяжение: \"−\"))"))
        self.label_text_4_2.setText(_translate("main_window", "N"))
        self.line_edit_4_1.setText(_translate("main_window", "20000"))
        self.label_text_4_3.setText(_translate("main_window", "кг (1 тс = 10^3 кг)"))
        self.label_text_5_1.setText(
            _translate("main_window", "Продольная сила от постоянной и длительной нагрузки:    "))
        self.label_text_5_2.setText(_translate("main_window", "N1"))
        self.line_edit_5_1.setText(_translate("main_window", "18000"))
        self.label_text_5_3.setText(_translate("main_window", "кг"))
        self.geo_label.setText(_translate("main_window", "Геометрические характеристики сечения"))
        self.label_text_6_1.setText(_translate("main_window", "Ширина сечения:"))
        self.label_text_6_2.setText(_translate("main_window", "b"))
        self.line_edit_6_1.setText(_translate("main_window", "150.0"))
        self.label_text_6_3.setText(_translate("main_window", "см"))
        self.label_text_7_1.setText(_translate("main_window", "Высота сечения:"))
        self.label_text_7_2.setText(_translate("main_window", "h"))
        self.line_edit_7_1.setText(_translate("main_window", "60.0"))
        self.label_text_7_3.setText(_translate("main_window", "см"))
        self.label_text_8_1.setText(_translate("main_window", "Защитный слой бетона растянутой зоны:"))
        self.label_text_8_2.setText(_translate("main_window", "a"))
        self.line_edit_8_1.setText(_translate("main_window", "5.0"))
        self.label_text_8_3.setText(_translate("main_window", "см"))
        self.label_text_9_1.setText(_translate("main_window", "Защитный слой бетона сжатой зоны:"))
        self.label_text_9_2.setText(_translate("main_window", "a\'"))
        self.line_edit_9_1.setText(_translate("main_window", "5.0"))
        self.label_text_9_3.setText(_translate("main_window", "см"))
        self.label_text_10_1.setText(_translate("main_window", "Площадь растянутой арматуры:"))
        self.label_text_10_2.setText(_translate("main_window", "As"))
        self.line_edit_10_1.setText(_translate("main_window", "11.31"))
        self.label_text_10_3.setText(_translate("main_window", "см^2"))
        self.label_text_11_1.setText(_translate("main_window", "Площадь сжатой арматуры:"))
        self.label_text_11_2.setText(_translate("main_window", "As\'"))
        self.line_edit_11_1.setText(_translate("main_window", "2.5"))
        self.label_text_11_3.setText(_translate("main_window", "см^2"))
        self.label_text_12_1.setText(_translate("main_window", "Диаметр арматуры:"))
        self.label_text_12_2.setText(_translate("main_window", "ds"))
        self.line_edit_12_1.setText(_translate("main_window", "1.2"))
        self.label_text_12_3.setText(_translate("main_window", "см"))
        self.beton_options_label.setText(_translate("main_window", "Характеристики арматуры и бетона"))
        self.label_text_13_1.setText(_translate("main_window", "Класс бетона на сжатие:"))
        self.comboBox_13.setCurrentText(_translate("main_window", "B20"))
        self.comboBox_13.setItemText(0, _translate("main_window", "B20"))
        self.comboBox_13.setItemText(1, _translate("main_window", "B10"))
        self.comboBox_13.setItemText(2, _translate("main_window", "B15"))
        self.comboBox_13.setItemText(3, _translate("main_window", "B25"))
        self.comboBox_13.setItemText(4, _translate("main_window", "B30"))
        self.comboBox_13.setItemText(5, _translate("main_window", "B35"))
        self.comboBox_13.setItemText(6, _translate("main_window", "B40"))
        self.comboBox_13.setItemText(7, _translate("main_window", "B45"))
        self.comboBox_13.setItemText(8, _translate("main_window", "B50"))
        self.comboBox_13.setItemText(9, _translate("main_window", "B55"))
        self.comboBox_13.setItemText(10, _translate("main_window", "B60"))
        self.label_text_14_1.setText(_translate("main_window", "Класс арматуры:"))
        self.comboBox_14.setItemText(0, _translate("main_window", "A500"))
        self.comboBox_14.setItemText(1, _translate("main_window", "A400"))
        self.comboBox_14.setItemText(2, _translate("main_window", "A600"))
        self.comboBox_14.setItemText(3, _translate("main_window", "B500"))
        self.comboBox_14.setItemText(4, _translate("main_window", "A240"))
        self.comboBox_14.setItemText(5, _translate("main_window", "A300"))
        self.restrictions_label.setText(_translate("main_window", "Ограничения"))
        self.label_text_15_1.setText(_translate("main_window", "Предельно допустимая ширина продолжительного \n"
                                                              "раскрытия трещин:"))
        self.label_text_15_2.setText(_translate("main_window", "a crc,ult,l"))
        self.line_edit_15_1.setText(_translate("main_window", "0.03"))
        self.label_text_15_3.setText(_translate("main_window", "см"))
        self.label_text_16_1.setText(_translate("main_window", "Предельно допустимая ширина непродолжительного\n"
                                                              "раскрытия трещин:"))
        self.label_text_16_2.setText(_translate("main_window", "a crc,ult"))
        self.line_edit_16.setText(_translate("main_window", "0.04"))
        self.label_text_16_3.setText(_translate("main_window", "см"))
        self.calculate_button.setText(_translate("main_window", "Рассчитать"))
        self.in_another_window_show.setText(_translate("main_window", "показать результат в новом окне"))
        self.file_menu.setTitle(_translate("main_window", "Файл"))
        self.info_menu.setTitle(_translate("main_window", "Инфо"))
        self.choose_db_menu.setText(_translate("main_window", "Выбрать базу данных..."))
        self.exit_menu.setText(_translate("main_window", "Выход..."))
        self.about_menu.setText(_translate("main_window", "О программе"))


class AskPlateUI:
    """ Ask plate area from PyQt6 \n
    label: area \n
    button: select_area_OK \n
    """

    def __init__(self, sofistik: Sofistik, dialog: QDialog):
        self.sofistik = sofistik
        self.ask_area = dialog

    def base_setup_ui(self) -> None:
        self.ask_area.setObjectName("Ask_area")
        self.ask_area.setEnabled(True)
        self.ask_area.resize(169, 94)
        self.area_label_text = QtWidgets.QLabel(self.ask_area)
        self.area_label_text.setGeometry(QtCore.QRect(10, 10, 161, 20))
        self.area_label_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.area_label_text.setObjectName("aria_label_text")
        self.area = QtWidgets.QSpinBox(self.ask_area)
        self.area.setGeometry(QtCore.QRect(20, 40, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.area.setFont(font)
        self.area.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.area.setObjectName("area_number")
        self.area.setMaximum(1000000)
        self.select_area_OK = QtWidgets.QPushButton(self.ask_area)
        self.select_area_OK.setGeometry(QtCore.QRect(100, 40, 51, 31))
        self.select_area_OK.setStyleSheet("background-color: rgb(89, 255, 0);")
        self.select_area_OK.setObjectName("select_area_OK")
        self.select_area_OK_pressed = QtGui.QAction(self.ask_area)
        self.select_area_OK_pressed.setObjectName("select_area_OK_pressed")

        # Hide area form when OK button is clicked
        self.select_area_OK.clicked.connect(self.ask_area.hide)

        self.translate_ui(self.ask_area)
        QtCore.QMetaObject.connectSlotsByName(self.ask_area)

    def translate_ui(self, ask_plate: QDialog):
        _translate = QtCore.QCoreApplication.translate
        ask_plate.setWindowTitle(_translate("Ask_area", "Выбор пластины"))
        self.area_label_text.setText(_translate("Ask_area", "Введите номер пластины"))
        self.select_area_OK.setText(_translate("Ask_area", "OK"))
        self.select_area_OK_pressed.setText(_translate("Ask_area", "area_selected"))
        self.select_area_OK_pressed.setToolTip(
            _translate("Ask_plate", "<html><head/><body><p>Select plate and press OK</p></body></html>"))
        self.select_area_OK_pressed.setShortcut(_translate("Ask_area", "Return"))
